version: '3.9'

services:
    trackservice:
        build:
            context: .
            dockerfile: Dockerfile.local
        container_name: trackservice
        ports:
            - "0.0.0.0:6002:6002"
        depends_on:
            - db
        networks:
            - qbreak-network
    db:
        image: "mcr.microsoft.com/mssql/server"
        volumes:
          - track_volume:/var/opt/mssql
        environment:
            SA_PASSWORD: "HW5etW#4iyWCNu"
            ACCEPT_EULA: "Y"
        ports:
            - "0.0.0.0:1533:1433"
        networks:
            - qbreak-network

volumes:
  track_volume:

networks:
    qbreak-network:
        external: true
